---
title: "MNIST"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### MNIST prediction with KNN

```{r include=FALSE}
library(caret)
library(tidyr)
library(dplyr)
library(ggplot2)
library(dslabs)
```

Load the data
```{r}
data("mnist_27") 
# Plot the data for digits 2 and 7
mnist_27$test%>% ggplot(aes(x_1, x_2, color = y)) + geom_point()
```

Create the train set
```{r}
x <- as.matrix(mnist_27$train[,2:3])
y <- mnist_27$train$y
```

Modeling
```{r}
knn_fit <- knn3(y ~ ., data = mnist_27$train, k = 5)
# Prediction
y_hat_knn <- predict(knn_fit, mnist_27$test, type= "class")
# Confusion Marix
confusionMatrix(data= y_hat_knn, reference = mnist_27$test$y)$overall["Accuracy"] 
```

Crossvalidation with default values in caret
```{r}
train_knn <- train(y ~ ., method = "knn", data = mnist_27$train)
ggplot(train_knn, highlight = TRUE)
```

Crossvalidation with trainControl and tuneGrid
```{r}
control <- trainControl(method = "cv", number = 10, p = 0.9) 
train_knn_cv <- train(y ~ ., method = "knn",                     
                      data = mnist_27$train,                    
                      tuneGrid = data.frame(k = seq(9, 71, 2)),                    
                      trControl = control) 
ggplot(train_knn_cv, highlight = TRUE)
```

```{r}
train_knn_cv$bestTune 
train_knn_cv$finalModel
```

Plot the accuracy
```{r}
train_knn_cv$results %>%    
  ggplot(aes(x = k, y = Accuracy)) +   geom_line() +   geom_point() +   
  geom_errorbar(aes(x = k,
                    ymin = Accuracy - AccuracySD,                      
                    ymax = Accuracy + AccuracySD))
```

Prediction
```{r}
Pred_knn_cv <- predict(train_knn_cv, mnist_27$test,type="raw")
# confusion matrix
cm <- confusionMatrix(Pred_knn_cv, mnist_27$test$y)
cm
```

```{r}
cm$overall["Accuracy"] 
```
